### ISSUE TITLE
Conflict with Heroku Toolbelt?

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/parity#101]
I followed the installation instructions:
```
~ % brew tap thoughtbot/formulae
~ % brew install parity
==> Installing parity from thoughtbot/formulae
Error: You must `brew link heroku` before thoughtbot/formulae/parity can be installed
```

So I tried that:

```
~ % brew link heroku
Linking /usr/local/Cellar/heroku/3.43.7...
Error: Could not symlink bin/heroku
Target /usr/local/bin/heroku
is a symlink belonging to heroku-toolbelt. You can unlink it:
  brew unlink heroku-toolbelt

To force the link and overwrite all conflicting files:
  brew link --overwrite heroku

To list all files that would be deleted:
  brew link --overwrite --dry-run heroku
```
Any advice on what I should do here? I don't want to break my existing Heroku setup.

**Comment by geoffharcourt** [comment]
Hey @andyw8, I haven't looked at making this a soft dependency (not explicitly requiring it), as I think ensuring users have heroku-toolbelt installed will help avoid confusion. If we didn't have this requirement I'd worry about users getting confusing error messages when the `heroku` executable didn't exist. 

I don't know a reason why you shouldn't always be using a recent, up-to-date heroku-toolbelt, and Homebrew provides that. My recommendation would be to install and link toolbelt from Homebrew.

If you want to use parity without a Homebrew conflict, you could install the software directly from the [releases](https://github.com/thoughtbot/parity/releases) page.

If you want to discuss changes to the formula further, let's create an issue on thoughtbot/homebrew-formulae, as this issue appears to be more about the formula rules than parity's own source code.

**Comment by andyw8** [comment]
Thanks for the advice. I've linked it using the `--overwrite` option and all seems ok.
