### ISSUE TITLE
Unknown database: DATABASE_URL. Valid options are: 

### ISSUE THREAD

**Issue by 8vius** [thoughtbot/parity#102]
I get this error when I try to update my staging server either from production or development. Am I missing a configuration or something?

**Comment by geoffharcourt** [comment]
@8vius, does your staging environment have a `DATABASE_URL` defined? You can check with `staging config`. We rely on that environment variable to be where your app's database is found (it's often duplicated by a database-specific color-named variable).

**Comment by 8vius** [comment]
@geoffharcourt yes, it is defined.

**Comment by geoffharcourt** [comment]
Hi @8vius can you paste the entire output of the error, and check that `DATABASE_URL` is also defined on production? I've never encountered this error with Parity, and want to see what specific circumstances might be causing it.

**Comment by geoffharcourt** [comment]
Please check back if you can post the output. I'm unable to help without further information.
