### ISSUE TITLE
Allow migrations to be skipped

### ISSUE THREAD

**Issue by fabn** [thoughtbot/parity#104]
Now that Heroku provides [release phase](https://devcenter.heroku.com/articles/release-phase) and [advice to use it](https://devcenter.heroku.com/changelog-items/908) to run database migrations it would be nice to have a way to skip migrations when using parity.

Release phase is better because new code will be deployed only when release command is executed successfully and since db migrations on postgres are transactional it is a better way to run them.

In this way you don't need to restart the app twice to be sure that code reads updated schema.

What do you think?

**Comment by geoffharcourt** [comment]
@fabn I'm definitely interested in leveraging this functionality. While this feature is in beta and has known bugs I'd like to wait until it's in general availability before we shape Parity to conform to it.

Leaving this issue open to track the release progress of the feature.

**Comment by fabn** [comment]
@geoffharcourt an immediate improvement that user can benefit from could be something like this:

```ruby
def skip_migrations?
  File.exist?('Procfile') && File.read('Procfile').match(/release:.*rake\s+db:migrate/)
end
```

In this way if a project is using this feature would not have his migrations run by parity.

**Comment by geoffharcourt** [comment]
Hi @fabn, small question: 

If you don't want to run migrations, at that point isn't it easy enough to just `git push production`? I see value in making migrations optional, but since we're not doing anything in the `deploy` command other than push and run migrations, this seems like it can be accomplished with no code.

**Comment by geoffharcourt** [comment]
I'm closing this out for now. We can reopen it if there's further discussion to be had. 

I'm a little squeamish about supporting functionality that we're not regularly using on projects at the moment, as it makes it harder to do acceptance testing for releases.
