### ISSUE TITLE
Installing parity executables on Ubuntu

### ISSUE THREAD

**Issue by trivett** [thoughtbot/parity#109]
Huge fan of Parity on OSX, but I can't seem to get it to work on Ubuntu. After gem install I get the following message:
```
##################################################
#  NOTE FOR UPGRADING FROM 0.9.3 OR EARLIER      #
##################################################

As of version 1.0.0, Parity no longer distributes its executables via Rubygems.

If you use apt or Homebrew to install dependencies, you can install Parity
through those package managers to get the `development`, `staging`, and
`production` executables. Installing the executables via package manager makes
the programs available across Ruby versions.

Users without access to those package managers or who prefer to self-install can
find the executables at our Github repository:

https://github.com/thoughtbot/parity
```
But there doesn't appear to be any apt repo to speak of. `apt-cache search parity` turns up nothing. Anyone else succeed in getting the production, staging and development executables to work on Ubuntu?

Ubuntu 16.04
Ruby version 2.2.2
git version 2.7.4
pg_restore (PostgreSQL) 9.5.5
heroku-toolbelt/3.43.14 (x86_64-linux) ruby/2.2.2
heroku-cli/5.5.5-789c5b7 (linux-amd64) go1.7.4

**Comment by pfac** [comment]
Got them working on a machine with Ubuntu. Download the package for Linux from [the releases page](https://github.com/thoughtbot/parity/releases), extract it somewhere on your system and [add the `/bin` to the `PATH` environment variable](http://askubuntu.com/questions/141718/what-is-the-path-environment-variable-and-how-do-i-add-to-it). Cheers

**Comment by geoffharcourt** [comment]
@pfac thank you for the advice! We're going to look to get this distributed to package managers so it's easier to install in the future.
