### ISSUE TITLE
Consider supporting and encouraging usage of heroku pipelines

### ISSUE THREAD

**Issue by djcp** [thoughtbot/parity#115]
You're probably aware of them, but [pipelines](https://devcenter.heroku.com/articles/pipelines) may be able to improve or supplant some of the workflows parity provides.

**Comment by geoffharcourt** [comment]
Hey @djcp that's certainly been on my mind.

My next priority (after getting 2.0.0 on Homebrew) is to remove Traveling Ruby and stabilize distribution to non-macOS OSes for the longer-term.

**Comment by geoffharcourt** [comment]
I'm going to close this out until we have a PR. Thanks for the idea!
