### ISSUE TITLE
[Backups] Heroku CLI breaking changes as of Dec 15 2016

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#117]
https://blog.heroku.com/the-new-heroku-cli

Heroku's CLI release has breaking changes that affected the output we used to process backups and restores. 

Options for resolution:

- Grep the new output format
- Use JSON format output and parse with `jq`
- Rewrite Parity as a plugin
- Abandon backup/restore commands

**Comment by gabebw** [comment]
I agree with what you just said in Slack: parsing JSON with `jq` is likely the best path forward. Though maybe using it as a plugin allows better integration?

I know I'm not the maintainer, but I do really appreciate using the backup/restore commands.  They're one of my most-used commands; certainly they save me the most time.

**Comment by geoffharcourt** [comment]
UPDATE: the backup/restore failures may have been resolved in an auto-update, but given the number of changes that recently happened I think moving away from relying on unformatted output is not safe.

**Comment by geoffharcourt** [comment]
I'm closing for now, since we haven't had any breaking changes to the CLI since this issue opened.
