### ISSUE TITLE
Deploy other branch to production?

### ISSUE THREAD

**Issue by ledermann** [thoughtbot/parity#132]
I'm trying to use **parity** for deploying a branch named `stable` to production. This seems not to be possible, because there is a hard-coded `git push production master`:

https://github.com/thoughtbot/parity/blob/c6b8fc9ea2688d254e645440c9a4cc5abcc7aa6f/lib/parity/environment.rb#L51

Is this intended? How to configure the branch used for production deployment?

**Comment by geoffharcourt** [comment]
Hi @lederman this is intended functionality (intended to prevent accidental deploying of a feature branch to production). Are you pushing `stable` on your local machine to `master` on Heroku?

We've shied away from building configuration options or accommodating a configuration file. If it doesn't make using or packaging Parity significantly more complicated I would be happy to look at a PR.

**Comment by ledermann** [comment]
@geoffharcourt yes, I want to push my `stable` branch to `heroku:master` (like `git push production stable:master --force`).

Maybe this is not a good practice. For my project I will think about another branching model like git-flow, where the branch for production deploy is `master`. This seems to be better fit with **parity**.

**Comment by geoffharcourt** [comment]
I think if you're using Heroku it makes sense to have your local `master` line up with the production app's `master`. On a recent client project I worked on, the GitHub base branch wasn't `master`, which helped make this flow work.

I don't think it's likely we'll ever append the `--force` argument for production deploys, but I think it may get passed along as an argument.

**Comment by ledermann** [comment]
You are right, thanks for your detailed explanation!
