### ISSUE TITLE
ERROR:  relation does not exist

### ISSUE THREAD

**Issue by hundsim** [thoughtbot/parity#137]
I can successfully import db from development to staging, but exporting from production to development results in `WARNING: errors ignored on restore: 54`, like this one:

    pg_restore: dropping FK CONSTRAINT events fk_rails_2551b6fe99
    pg_restore: [archiver (db)] Error from TOC entry 3013; 2606 169195 FK CONSTRAINT events fk_rails_2551b6fe99 gtdxahketybicf
    pg_restore: [archiver (db)] could not execute query: ERROR:  relation "public.events" does not exist
    Command was: ALTER TABLE ONLY "public"."events" DROP CONSTRAINT "fk_rails_2551b6fe99";

What in my setup may I have missed?  If the `config/database.yml` has to be in a certain format - is there any sample file to look at?

**Comment by geoffharcourt** [comment]
@hundsim a couple questions so we can track down what's going on:

1. Do you know what version of parity you're running?
2. How did you install parity (Homebrew, apt, Rubygems)?
3. What does your `database.yml` look like? Can you paste it here without the `password` lines?

**Comment by croaky** [comment]
May not be related, but I just noticed Parity may want to use the `--if-exists` flag in the `dropdb` invocation.

Could also add a [Issue Template](https://github.com/blog/2111-issue-and-pull-request-templates) to request issue reporters include `which development`, `brew list parity`, etc

**Comment by geoffharcourt** [comment]
Please let me know if you have more detail we can use to diagnose!
