### ISSUE TITLE
Etc.nprocessors breaks compatibility with ruby 2.1.x

### ISSUE THREAD

**Issue by eignerchris** [thoughtbot/parity#143]
https://github.com/thoughtbot/parity/blob/c05fd7aab4a2d934303b84d69b2c54b2f113a26a/lib/parity/backup.rb#L75

Looks like `Etc.nprocessors` method was introduced in ruby 2.2.

Docs from pg_restore say: "A good place to start is the number of CPU cores on the server, but **values larger than that can also lead to faster restore times in many cases**"

Given that last statement, is there any harm in using a best-guess of 4?

Slightly more complex solution: check for the presence of `nprocessors`, otherwise use the best-guess of 4.

**Comment by geoffharcourt** [comment]
Hrm. We should be very thoughtful about what we do here. Ruby 2.1 is EOLed, so I don't want to tie ourselves in knots with a solution if there's not a very clean one.

**Comment by geoffharcourt** [comment]
@eignerchris, I've authored a potential fix in #144.
