### ISSUE TITLE
restore-from fails

### ISSUE THREAD

**Issue by dbinetti** [thoughtbot/parity#146]
Help us track down and resolve parity problems faster with this template.

## What command did you execute?
`(barberscore-api)bash-3.2$ development restore-from production`
## What did you expect to happen?
Restore from backup
## What actually happened?
```
(barberscore-api)bash-3.2$ development restore-from production
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59.1M  100 59.1M    0     0  5412k      0  0:00:11  0:00:11 --:--:-- 9602k
pg_restore: [archiver] unsupported version (1.13) in file header
(barberscore-api)bash-3.2$ 
```
## Some information about your installation

- What's your operating system?
macOS Sierra 10.13.3

- What's the output of `which development`, `which staging`, `which production`?
  Parity has had multiple installation channels, and it's not uncommon for an
  old version to be somewhere else in your path.
```
(barberscore-api)bash-3.2$ which development
/usr/local/bin/development
(barberscore-api)bash-3.2$ which staging
/usr/local/bin/staging
(barberscore-api)bash-3.2$ which production
/usr/local/bin/production
```

- If installed via Homebrew, what does `brew list parity` output?
```
(barberscore-api)bash-3.2$ brew list parity
/usr/local/Cellar/parity/2.4.0/bin/development
/usr/local/Cellar/parity/2.4.0/bin/production
/usr/local/Cellar/parity/2.4.0/bin/staging
/usr/local/Cellar/parity/2.4.0/lib/parity/ (5 files)
/usr/local/Cellar/parity/2.4.0/lib/parity.rb
```

- If installed via Rubygems, what's the gem version?

N/A

**Comment by dbinetti** [comment]
I should also mention it has been working flawlessly; I've only been updating application code so I'm not sure what's causing it to fail.  Local Postgres and Heroku Postgres both 10.2

**Comment by yun313350095** [comment]
me too

**Comment by geoffharcourt** [comment]
I'm seeing this as well. We saw some automated backups outside of Heroku (not using Parity) fail for a similar reason. I'm not sure what the issue is, but I suspect this is a bigger problem. I'm going to try executing the commands for download and restore separately, if you could all do the same that would be helpful.

**Comment by geoffharcourt** [comment]
I can't download the files with curl using the command we currently use in the code (macOS, High Sierra 10.13.3) due to an error with libcurl. I am now curious if Heroku used to expose these DBs using HTTP and now they are HTTPS. @yun313350095 are you also on macOS?

**Comment by geoffharcourt** [comment]
I am able to download using wget, so that may be the easiest way to fix this beyond having people do a customized installation of curl with Homebrew.

**Comment by geoffharcourt** [comment]
Hi, the issue seems to be that Heroku did an upgrade for a vulnerable patch version of PG 9.6.x. You need to update your local PG version to 9.6.8 or 10.3.x to resolve the issue.

https://www.postgresql.org/docs/9.6/static/release-9-6-8.html

**Comment by dbinetti** [comment]
Not for me -- on current versions both local and prod, and have been
throughout.  was the first thing I checked.

**Comment by dbinetti** [comment]
now functional again.  not sure what changed, but perhaps was on the Heroku side.  regardless, working and closing.
