### ISSUE TITLE
Error: No available formula with the name "homebrew/core/heroku" (dependency of thoughtbot/formulae/parity)

### ISSUE THREAD

**Issue by joshRpowell** [thoughtbot/parity#161]
Help us track down and resolve parity problems faster with this template.

## What command did you execute?

```
brew reinstall parity
```

## What did you expect to happen?

A clean install

## What actually happened?

```
homebrew/core/heroku was deleted from homebrew/core in commit f3c308ab5:
  heroku: remove formula.
```

Parity depends on heroku-toolbelt
https://github.com/thoughtbot/homebrew-formulae/blob/8cd787efaa9881c7e3a93ba2028b216f7fa34e71/Formula/parity.rb#L24

![1 zsh 2018-10-22 13-41-14](https://user-images.githubusercontent.com/6732638/47308808-b207cd80-d600-11e8-855d-acbc3fb91f2b.png)

This is the Homebrew PR where this formula was removed https://github.com/Homebrew/homebrew-core/pull/33233

## Some information about your installation

- What's your operating system? 
  - macOS 10.14
- What's the output of `which development`, `which staging`, `which production`?
  Parity has had multiple installation channels, and it's not uncommon for an
  old version to be somewhere else in your path.
  - nothing
- If installed via Homebrew, what does `brew list parity` output?
  - nothing 
- If installed via Rubygems, what's the gem version?

**Comment by joshRpowell** [comment]
not sure how I missed this PR https://github.com/thoughtbot/homebrew-formulae/pull/53

it should resolve this issue.

**Comment by mjankowski** [comment]
I'm closing this on the assumption that the linked issue sorted it out, please reopen if not.
