### ISSUE TITLE
calling parity for customized environments without putting `bin/` before the environment

### ISSUE THREAD

**Issue by concept47** [thoughtbot/parity#172]
Help us track down and resolve parity problems faster with this template.

## What command did you execute?
`staging2 deploy`

## What did you expect to happen?
I have a binstub in `bin/staging2` that works when I call `bin/staging2 deploy` I expected that to be called when I executed `staging2 deploy`

## What actually happened?
-bash: staging2: command not found

I know this is probably a newb issue. But I just wanted to figure out how to make my customized environments execute without having to type bin/ in front of them

## Some information about your installation
- What's your operating system? Mac OS

- If installed via Homebrew, what does `brew list parity` output? n/a
- If installed via Rubygems, what's the gem version? 3.2.0

**Comment by geoffharcourt** [comment]
Hi! 

You can solve this issue with [this .git/safe trick](https://thoughtbot.com/blog/git-safe) from the thoughtbot blog. It allows you to put everything in `bin` into your path only for repositories you trust.
