### ISSUE TITLE
Did you mean autosuggest somehow broken

### ISSUE THREAD

**Issue by iDuuck** [thoughtbot/parity#185]
Help us track down and resolve parity problems faster with this template.

## What command did you execute?

```
staging deployu
```

## What did you expect to happen?

I expected that the "Did you mean" engine, that it tells me: "Did you mean: deploy".

## What actually happened?

![image](https://user-images.githubusercontent.com/325241/90401749-b25b3d80-e09e-11ea-9e8b-db8142fb722a.png)

## Some information about your installation

- What's your operating system?
- What's the output of `which development`, `which staging`, `which production`?
  Parity has had multiple installation channels, and it's not uncommon for an
  old version to be somewhere else in your path.
- If installed via Homebrew, what does `brew list parity` output?
- If installed via Rubygems, what's the gem version?

**Comment by geoffharcourt** [comment]
Thanks for reporting!

The parity-specific commands (`deploy`, `migrate`, `tail`, etc.) aren't going to work with Heroku's autocomplete or did-you-mean correction. `deploy` isn't a Heroku command, and their CLI won't recognize it. 

For us to handle this, we'd have to implement our own did-you-mean handler, and that seems like a prohibitively expensive undertaking and probably hard to do without requiring new gem dependencies.

If there's a straightforward PR that can fix this I'd be open to the change, but I don't think this is feasible unfortunately.
