### ISSUE TITLE
Run tasks using parity

### ISSUE THREAD

**Issue by Vin0uz** [thoughtbot/parity#193]
👋 

First of all, thanks for Parity, I love it ! 

I often run tasks manually on my staging environnement, and end up doing a boring `heroku run rails foo:bar --remote staging`  and I've been wondering if we could add this possibility, and have something like `staging task foo:bar` ? I can propose a diff if you guys agree with it :)

**Comment by geoffharcourt** [comment]
@Vin0uz this is already doable with `staging run rake foo:bar`! `staging` acts as `heroku <all passed args> --remote staging`.

**Comment by Vin0uz** [comment]
Oh right ! I naively thought about skipping the `run` part 🤦‍♂️ 
Thanks for clearing this up 👍
