### ISSUE TITLE
How to install parity without upgrading postgresql package?

### ISSUE THREAD

**Issue by vfonic** [thoughtbot/parity#195]
I have postgresql 13.3 installed via Homebrew. It works great and I have some other packages (postgis) that have postgresql as its dependency. I also have several databases that I don't want to mess up.

I want to install parity and have it use current postgresql 13.3. I don't want to upgrade postgresql just so I can install parity.

Please note that I had parity installed earlier today and it was working with current postgresql 13.3 just fine.

How can I install parity, without upgrading postgresql package? Thanks!

## What command did you execute?

`brew install parity`

## What did you expect to happen?

It install parity and uses existing (homebrew installed) postgreql package.

## What actually happened?

I got the following error:

> Error: You must `brew unpin postgresql` as installing thoughtbot/formulae/parity requires the latest version of pinned dependencies

## Some information about your installation

- What's your operating system? macOS Big Sur 11.6
- What's the output of `which development`, `which staging`, `which production`? `development not found`, `staging not found`, `production not found`
  Parity has had multiple installation channels, and it's not uncommon for an
  old version to be somewhere else in your path.
- If installed via Homebrew, what does `brew list parity` output? N/A
- If installed via Rubygems, what's the gem version? N/A

**Comment by vfonic** [comment]
Got it, this works:

```sh
brew install thoughtbot/formulae/parity --ignore-dependencies
```

**Comment by geoffharcourt** [comment]
It might be time to stop making PG a dependency, there's a lot of value in parity IMO even if you don't use the DB features.
