### ISSUE TITLE
Error on development restore call

### ISSUE THREAD

**Issue by Vin0uz** [thoughtbot/parity#196]
## What command did you execute?
`development restore production`

## What actually happened?
After downloading the dump, restoring it fails with `visit_Psych_Nodes_Alias': Unknown alias: default (Psych::BadAlias)` error message. 

## Some information about your installation
This issue started with our bump to ruby 3 and Rails 7

Does anyone else faced it ? 

-- 
I tried to identify the problem more precisely but no real success.. My only guess would be about [this line in yaml](https://github.com/ruby/yaml/blob/47b9e3067014e02f06287563788c19fe22b2bba9/Gemfile#L10) and possible conflict (ruby 3 in my repo but 2.5 in parity') 🤷‍♂️

**Comment by multiplegeorges** [comment]
@Vin0uz My fork fixes this issue if you need something before Thoughtbot merges my PR. Just fyi.
