### ISSUE TITLE
Restoring development from heroku broken since heroku_ext change

### ISSUE THREAD

**Issue by KevinButterfield** [thoughtbot/parity#200]
Ever since https://devcenter.heroku.com/changelog-items/2446, Heroku's postgres extensions are installed in the new `heroku_ext` schema.  However, `development restore-from *` fails, as once the local database is dropped and recreated, it has no `heroku_ext` schema.

This causes `pg_restore` to raise errors.  If the extensions are not related to actual table data, these errors are fairly benign, but if an extension is directly tied to data (e.g. `citext` adding a new column type) this is catastrophic. 

Please compensate for this by adding the `heroku_ext` schema to newly re-created development databases before running pg_restore.

**Comment by croaky** [comment]
How's https://github.com/thoughtbot/parity/pull/201 look?

**Comment by KevinButterfield** [comment]
It looks great!  Thank you!

**Comment by geoffharcourt** [comment]
Closed in #201! Thanks @croaky.
