### ISSUE TITLE
Update to use new Heroku PG syntax

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#29]
Heroku resolved the issue with the PG backup URL not being passed along that triggered https://github.com/croaky/parity/issues/23 ([see comment](https://github.com/heroku/heroku/issues/1466#issuecomment-88537501)). We can now go ahead and  reapply https://github.com/croaky/parity/pull/22 and take advantage of the new command form at some point before Heroku deprecates the old one.

**Comment by geoffharcourt** [comment]
Update: as of this morning, Heroku Toolbelt 3.30.4 contains the necessary fixes to enable using the new `pg:backups public-url` syntax.

**Comment by mjankowski** [comment]
I will pay $1 to have this merged.

**Comment by geoffharcourt** [comment]
After doing a little testing, I think we need to wait a month or so to be sure users have updated their versions of Heroku Toolbelt. I was testing against Ruby 2.1.5 where I forgot I still had the old (pre-3.30.4) Toolbelt installed, and we got the same errors that required reverting 5e789c328040491b3dec7436bdc48f31dbf7c618.

**Comment by geoffharcourt** [comment]
@croaky, Heroku emailed out today to inform users that the old PG Backups is being retired over the coming week. I'll prepare the PR, but we should probably release as soon as a few folks have been able to test to prevent users from temporarily losing parity functionality.

**Comment by gabebw** [comment]
I'd like to get this merged as well. Looks like it's a simple `git revert` https://github.com/thoughtbot/parity/commit/4bba15fc62ac5220e72717113b6561fcafbb3e00 ?

**Comment by gabebw** [comment]
I just updated my local copy to use those changes and it worked great.

**Comment by geoffharcourt** [comment]
@gabebw, it's not just reverting 4bba15f. That commit didn't incorporate some necessary changes to the new pg:backups syntax that are needed for the commands to work.
