### ISSUE TITLE
Ensure we return exit status from Heroku when errors happen

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#35]
I noticed while testing fb13da9 that when the `production backup` command failed that it did not halt execution of a statement like this: 

```zsh
production backup && development restore production
```

Given that the second event is dependent on the first, we probably should return the exit status of whatever `Kernel.system` executes if it indicates an unsuccessful execution.

**Comment by croaky** [comment]
Attempt in https://github.com/thoughtbot/parity/pull/37
