### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#36]
I'm concerned Heroku is going to start dropping support, so I want to get this out in the wild first.

@croaky, could you push to Rubygems?

I don't have access to the Homebrew formula, so if @croaky, @gabebw, or @JoelQ could update the Homebrew formula with [the v0.7.0 release](https://github.com/thoughtbot/parity/releases/tag/v0.7.0), I would very much appreciate it.

**Comment by jayroh** [comment]
I'll butt in here too and say that I, too, would love to test this w/the homebrew version. Just a couple of days ago updated everything to latest heroku toolchain, and parity via homebrew.

... reluctant +1. I dislike +1's

**Comment by croaky** [comment]
Yup I'll do this tonight.

**Comment by croaky** [comment]
@jayroh We'll accept +1's in the form of bulldog photos.

**Comment by croaky** [comment]
Pushed to Rubygems. Gave y'all access. @jayroh Looks like you're overdue to update your Rubygems.org email address.

**Comment by croaky** [comment]
@jayroh @geoffharcourt I also gave you write access to thoughtbot-formulae in case you need to update the Parity formulae in the future.

**Comment by jayroh** [comment]
![](http://media.giphy.com/media/IWukN7I7hKM8g/giphy.gif)

nice - thanks @croaky ... For the reminder too. You're right that's way way overdue.
