### ISSUE TITLE
Bypass confirmation for staging?

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#38]
In https://github.com/thoughtbot/parity/pull/21 we added the ability to pass the `--confirm appname-staging` argument to `staging restore` so that users could bypass the confirmation, script the restore, etc. Is there a good reason not to always pass the confirm parameter to `stating restore`? I agree with the philosophy of not allowing Parity to overwrite production out of fear users might inadvertently blow away their production DB, but it seems that staging should never be in a state where you couldn't rebuild the state you're in or just replace it with whatever's in production.

This change is easy from a coding perspective, but I'm want to see if there's consensus around making this more streamlined.

**Comment by geoffharcourt** [comment]
@croaky, @JoelQ, @gabebw, wanted to get your read on this. I normally consider staging volatile and never assume that data that sits there needs to be shielded from overwriting restores, but I want to be sure I'm not unique in that regard. 

Always passing the `--confirm` switch on means you can run `production backup && staging restore production` and then go get your coffee while the two operations execute in sequence.

**Comment by JoelQ** [comment]
>  I normally consider staging volatile and never assume that data that sits there needs to be shielded from overwriting restores, but I want to be sure I'm not unique in that regard.

Agreed. On greenfield projects, I'll often run `rake db:reset` on staging multiple times a week. While that isn't the case on more established projects, I still consider staging to be volatile.

My main concern here is that users may be surprised when the don't get a confirmation and may inadvertently blow away their staging data (particularly annoying if they built it by hand instead of using a script). Thoughts on making this behavior opt-in, perhaps via some type of config?

**Comment by geoffharcourt** [comment]
Are you thinking a `.parity` config file or an environment variable?

**Comment by geoffharcourt** [comment]
Actually, if we're going to do any kind of configuration, it should probably be a config file, so that the setting is respected by any scripts that use parity and might not have environment variables loaded.

**Comment by JoelQ** [comment]
Probably `.parity`. I just want a way for users to explicitly say "Yes, don't ask for confirmation again"

**Comment by geoffharcourt** [comment]
I realized we're already configuring settings in an app initializer, so I kept all the configuration there. It does mean the opt-in will be at the application rather than the user level. If that still seems unsafe I can add the machinery for a config file.

**Comment by croaky** [comment]
Should we close this issue in light of https://github.com/thoughtbot/parity/pull/44?

**Comment by geoffharcourt** [comment]
I really wanted to get this addition in, but in light of all of the benefits we gain from tossing the config apparatus in #44, I am OK dropping it unless we want to unilaterally declare staging data to be volatile.

**Comment by croaky** [comment]
What are some example staging commands that we've been running lately that we've been feeling the need to add --confirm to automatically? Is it specs ally restore or others, too?

**Comment by geoffharcourt** [comment]
I think `restore` is the only one that I would want to use it for. I push fairly frequent changes to staging so that my co-founder can view them on his phone against real data, and I want to bring production data down to staging fairly often.

When I'm working on a single app for along time I can alias this locally.
