### ISSUE TITLE
Enable/disable maintenance on deploy?

### ISSUE THREAD

**Issue by gjorquera** [thoughtbot/parity#40]
I'm currently enabling maintenance mode before deploy and disabling it after it has succeed. So, if there's an error, I don't have users banging against a bad deploy.

Is there a reason not to use that heroku feature for `production deploy`?

Am I missing something?

**Comment by geoffharcourt** [comment]
Hi @gjorquera, not all deploys require downtime. I think many developers would prefer not to trigger downtime (particularly if you are testing first against a staging instance).

If you want to enable functionality like that, I think wrapping `production deploy` in a shell script that enable maintenance mode, runs the deploy, then disables maintenance mode would be the best practice.

**Comment by gjorquera** [comment]
Ok, I understand. I'll wrap it on a shell script then.
Thanks!
