### ISSUE TITLE
db/schema.rb fall back to db/structure.sql

### ISSUE THREAD

**Issue by croaky** [thoughtbot/parity#43]
Have a Rails app or two that's needed to switch to SQL dump.

**Comment by geoffharcourt** [comment]
@croaky, is this meant to say falling back from `db/schema.rb` to structure?

**Comment by croaky** [comment]
@geoffharcourt Yup, good call, updated.

**Comment by croaky** [comment]
Derp. We read from `config/database.yml`, don't need to fall back when schema structure type changes.
