### ISSUE TITLE
Reset development database on `development restore x`?

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#47]
I've been having an issue recently where some primary keys and pre-existing data in development has caused conflicts when trying to restore a production/staging snapshot on development. I've fixed this by running `rake db:reset` before `development restore production`. I'm starting to think that always resetting (or even dropping and recreating) the development database might be good practice before bringing down data from Heroku.

The advantage of always doing this is that we'll be very sure there's no vestigial data/metadata left in the database, but the disadvantage is that if the backup is unavailable on Heroku for some reason, you lose your existing development database before we know there was a restore problem. I think this is a worthwhile tradeoff, but curious to see if other users have had a similar experience.

**Comment by croaky** [comment]
When I do these restores, I typically want a complete copy of the env's database, would prefer not to mix. Agree that resetting would be expected.

**Comment by geoffharcourt** [comment]
I've run into this a couple times on my latest project where I had migrations run on my development database from a feature branch, then pulled from staging, then tried to migrate again and couldn't because the tables already existed. I'll start work on this feature.

**Comment by geoffharcourt** [comment]
It looks like now Heroku as of a recent version of the CLI expects there to be no development database in place before `pg:pull` runs, so they're thinking about this the same way we were.
