### ISSUE TITLE
Don't run `migrate` when deploying non-Rails apps

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#49]
Experimenting with a Python app we're using at @cortexintel and the Homebrew version of Parity has been useful. The `deploy` command runs fine, but gives us some errors about migrations.

Wondering if we should detect if it's a Rails app before we decide to run `migrate`.

**Comment by croaky** [comment]
Makes sense to me. We also have `bin/deploy` scripts in most of our apps. Thoughts on removing the `deploy` command in Parity?

**Comment by geoffharcourt** [comment]
I was against adding `deploy` when it was first suggested, but it's become pretty essential as I've started working on a wider number of apps at a time. On our latest project, we're actually using parity in our `bin/deploy` script.

I'm thinking about 1) checking to see if `rake` is a valid command and 2) checking if `migrate` is a valid task. Would looking for the existence of `db/migrate` be a better strategy?
