### ISSUE TITLE
could not find app name in production git remote

### ISSUE THREAD

**Issue by chrise86** [thoughtbot/parity#51]
Every time I try running `production console` I get:

    could not find app name in production git remote

Other commands such as `production logs` work fine.

OSX 10.11

**Comment by geoffharcourt** [comment]
Hi chrise86, can you paste in the output of `git remote -v`, `pwd`, and `heroku --version`? I assume if you're running `heroku console`, then you're using Tim Pope's (somewhat aggressively named) `heroku-fucking-console`, otherwise `console` isn't supported without `run` as a prefix.

**Comment by JuanitoFatas** [comment]
Same here.

`git remote -v`

```
origin	git@github.com:jollygoodcode/dasherize.git (fetch)
origin	git@github.com:jollygoodcode/dasherize.git (push)
production	git@heroku.work:dasherize-production.git (fetch)
production	git@heroku.work:dasherize-production.git (push)
```

`pwd`:

```
/Users/Juan/jollygoodcode/dasherize
```

`.git/config`:

```
[remote "production"]
	url = git@heroku.work:jollygoodcode-production.git
	fetch = +refs/heads/*:refs/remotes/production/*

```

`heroku --version`:

```
heroku-toolbelt/3.42.15 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.25.1-332e03c (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-accounts
heroku-apps@0.2.2
heroku-cli-addons@0.0.1
heroku-fork@3.1.4
heroku-git@2.4.1
heroku-local@4.1.3
heroku-run@2.7.1
heroku-status@1.2.1
```

And when I do `production logs`:

```
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
```

parity install via homebrew, `brew info parity`:

```
rew info parity
thoughtbot/formulae/parity: stable 0.7.0
https://github.com/thoughtbot/parity
/usr/local/Cellar/parity/0.7.0 (1025 files, 20M) *
  Built from source
From: https://github.com/thoughtbot/homebrew-formulae/blob/master/Formula/parity.rb
==> Dependencies
Required: git ✔, heroku-toolbelt ✔, postgres ✔
```

What am I missing? Thanks!

**Comment by winston** [comment]
I am facing the same problem as @JuanitoFatas. Am using https://github.com/heroku/heroku-accounts. Could that be the problem? 

Which means:

```
[remote "production"]
    url = git@heroku.work:repo-production.git
    fetch = +refs/heads/*:refs/remotes/production/*
```

doesn't work. Note `heroku.work` is required by heroku accounts to differentiate the accounts.

While

```
[remote "production"]
    url = git@heroku.com:repo-production.git
    fetch = +refs/heads/*:refs/remotes/production/*
```

with the regular `heroku.com` works.

Thank you!

**Comment by winston** [comment]
I just did a little digging and I noticed parity translates commands to:

```
heroku <command> --remote production
```

so when `production` is `git@heroku.work:repo-production.git`, then it fails with:

```
could not find app name in production git remote
```

but when `production` is `git@heroku.com:repo-production.git`, then it works.

So I guess it's probably a bug with Heroku's CLI instead. I'll log an issue there too. Thanks!

**Comment by winston** [comment]
Saw this https://github.com/heroku/heroku/issues/1751 and did `heroku git:remote -a appname -r remotename`. Then it worked! :)

**Comment by JuanitoFatas** [comment]
> Saw this heroku/heroku#1751 and did heroku git:remote -a appname -r remotename. Then it worked! :)

works for me, too.

**Comment by geoffharcourt** [comment]
Hi @winston and @JuanitoFatas, it looks like you've found and fixed on your own. I think we need a note in the README about using heroku-accounts in case other users. Were you both using the old heroku-accounts plugin in the past?

**Comment by winston** [comment]
@geoffharcourt Yes. Just upgraded to the heroku supported one.

**Comment by geoffharcourt** [comment]
Looks like we're all clear here, closing this out.
