### ISSUE TITLE
Allow for git push -f

### ISSUE THREAD

**Issue by vfonic** [thoughtbot/parity#56]
Thanks for great and simple CLI tool!

One issue I ran into today was that I couldn't use parity to make a force deploy.

I tried `production deploy -f` and, after that failed (ignoring -f argument), I resorted to `git push production master -f`. It would be good if parity would be able to do this.

Viktor

**Comment by vfonic** [comment]
Similarly, having `staging deploy feature-branch-name` would be quite handy.

I guess you'd have to change the implementation of `run_migration?` method (and probably couple of other things), as it's referring to master branch:
https://github.com/thoughtbot/parity/blob/df296fe6e77698fe4522b120944621667b1dcbd3/lib/parity/environment.rb#L112

**Comment by geoffharcourt** [comment]
I think force-pushing to non-production branches could be useful.

@vfonic, you can push feature branches to staging now as of df296fe6e77698fe4522b120944621667b1dcbd3 in v 0.8.0.

**Comment by geoffharcourt** [comment]
@vfonic force-pushing to production is probably not going to be on our roadmap. We try to avoid force-pushing to master to avoid conflicts with teammates. If something bad ends up on master, we would revert it with an additional commit rather than amending or editing a commit already pushed to master.

Force-pushing to staging or other feature environments makes sense, as you're likely to be amending or squashing your commits on the branch in progress.

**Comment by vfonic** [comment]
Thanks for the explanation. Indeed it makes total sense. I'll try force
pushing next week and let you know.

**Comment by geoffharcourt** [comment]
cc: @croaky @gabebw @joelq curious to get your thoughts on this. I don't mind force-pushing to staging, particularly when we're allowing feature branches to be pushed there. I think it's unlikely an unorthodox for staging to be the only place where code you want to keep might be stored, so blowing away an orphaned branch on staging seems low-risk. Any concerns?

**Comment by vfonic** [comment]
@geoffharcourt I've tried pushing feature branches. Works flawlessly. Thanks!

I've noticed that documentation doesn't mention this functionality:
https://github.com/thoughtbot/parity/blob/master/README.md#usage

It's actually wrong for non prod environments as it doesn't deploy master.
> Deploy from master, and migrate and restart the dynos if necessary:
>
    production deploy
    staging deploy

**Comment by JoelQ** [comment]
@geoffharcourt I think force-pushing to staging is completely normal, particularly if you've put a different branch on there.

**Comment by geoffharcourt** [comment]
Documentation will be updated in #66. Since we already provide for force-pushes, I'm closing this ticket.
