### ISSUE TITLE
Integration test application

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#65]
Our current system of stubbing out calls to `Kernel.system` is great for performance and isolation of the portions of Parity that we want to test, but I find myself testing certain non-passthrough commands like `deploy` and `migrate` on a dummy app I have on Heroku. 

Here's what I do:

1. roll back the database by one migration
2. roll back the repository to a commit before the migration
3. force-push the rolled-back repo to Heroku
4. run `production deploy`
5. revert production with Heroku CLI
6. run `production deploy` again

I'm wondering if this should be part of Parity or our Homebrew testing so we can be very confident what we're pushing out will not have possibly undetected problems with deploys.

**Comment by tabfugnic** [comment]
Having third party services can be troublesome. I have found great success with building out fake services that will better replicate what I'm trying to do. Thoughts on building out a Heroku fake?

**Comment by JoelQ** [comment]
:+1: to the idea of having a fake for external services in integration tests.

**Comment by geoffharcourt** [comment]
This would reduce a lot of anxiety for me. At the moment our release process involves me running a number of the most critical commands against a simple app I use that doesn't change much and doesn't have many moving parts.

**Comment by geoffharcourt** [comment]
I've reviewed the git/Github faking that happens in the https://github.com/github/hub application, and while I think their approach is not necessarily easy to follow, we can probably do something like it with fewer parts due to the specific dependencies our app has (we can stub out commands rather than having to stub API endpoints, etc). Any of you up for pairing on this next Friday?

**Comment by geoffharcourt** [comment]
I'm closing this out for now, as I don't expect to have the investment time to work on this in the near future, but we can reopen if need be.
