### ISSUE TITLE
Allow restoring to production

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/parity#70]
I came across this error today

> Parity does not support restoring backups into your production environment

While I understand the reasoning, it would be nice to have a way to override this if that's what I need to do. Maybe some type of y/n confirm to restore?

**Comment by geoffharcourt** [comment]
I'm opposed to making it interactive, but I think it's worth reconsidering pushing/restoring to production. If we implement automated backups before some actions per #71, maybe we could always back up production before restoring or pushing to it?

**Comment by geoffharcourt** [comment]
(opposed to making it interactive beyond the Heroku-issued confirmation prompt that already exists)

**Comment by jakecraige** [comment]
Perhaps even something as simple as a `--force` flag to skip this protection would be ideal

**Comment by geoffharcourt** [comment]
I think the Heroku-driven confirmation is probably sufficient if we opt to allow this kind of activity. @croaky I know you've had strong feelings in the past about this protection and a worry about users inadvertently blowing away their production database.

**Comment by danbee** [comment]
I've just hit this issue myself. +1 for the `--force` flag.

**Comment by geoffharcourt** [comment]
@danbee resolved this issue in #92!
