### ISSUE TITLE
Back up the database before deploy

### ISSUE THREAD

**Issue by croaky** [thoughtbot/parity#71]
e.g. https://github.com/thoughtbot/hub/commit/dadcf42d8e938f8c6b736ac4370af70dbca50df2

**Comment by JoelQ** [comment]
I like this. Does Heroku limit the number of backups you can have?

**Comment by croaky** [comment]
@joelq Yeah, it's some kind of cap with like an exponential back off. They keep like the last 10-15 manual / daily backups, then a few for week-month periods.

**Comment by geoffharcourt** [comment]
I'm mildly against this, as I like to deploy very frequently, and not every deploy needs a backup. Could we instead consider backing up the database before any migration activity occurs?

**Comment by JoelQ** [comment]
Don't we attempt to migrate the database on all deploys?

**Comment by geoffharcourt** [comment]
@JoelQ we only migrate the database if production didn't contain the commits with new migrations before the deploy.

**Comment by geoffharcourt** [comment]
@croaky @joelq we could run the backup only if we plan on running migrations later in the deploy. Would that accomplish the goal?

**Comment by geoffharcourt** [comment]
I don't think this workflow is compatible with a development workflow that ships often. I'm happy to reopen this if we want to revisit the issue later (perhaps with backing up before running migrations).
