### ISSUE TITLE
Parse ERB in `database.yml`

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#73]
Rails allows a user to use ERB within a YAML file to set up dynamic values for keys. On apps that employ this approach, Parity will fail when attempting to parse `config/database.yml`.

**Comment by bernerdschaefer** [comment]
@geoffharcourt Why does Parity parse `config/database.yml`?

**Comment by geoffharcourt** [comment]
@b, we need to know the names of the local development database.

**Comment by bernerdschaefer** [comment]
I see. So it's used to get information about the local database when running commands like: `development restore staging` and `staging restore development`.

**Comment by geoffharcourt** [comment]
@bernerdschaefer correct. We could make assumptions and force convention here, but I've had a number of client apps that have deviated from this standard and local edits of `database.yml` are sort of a headache to maintain.
