### ISSUE TITLE
Update readme for restore commands

### ISSUE THREAD

**Issue by creuter** [thoughtbot/parity#74]
When trying to `restore-from`:

```
hub master % staging restore-from production
 !    `restore-from` is not a heroku command.
 !    See `heroku help` for a list of available commands.
```

and from the README:

```
Restore a production database backup into staging:

`staging restore-from production`
```

Should this be `restore` and not `restore-from`?

**Comment by bernerdschaefer** [comment]
@creuter `restore-from` was [added recently](https://github.com/thoughtbot/parity/pull/67), but it doesn't look like its made it into a release yet.

**Comment by geoffharcourt** [comment]
Correct. I will try to get a new release out tomorrow.
