### ISSUE TITLE
Abandon Rubygems-installed executable?

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#77]
I think our experiment to distribute Parity as packages rather than through Rubygems has been a success. While working across several Ruby versions with different clients and projects, I've found having Parity be independent of my current Ruby version to be useful. When I have the gem executables installed because I've been testing development versions, I find the existence of shims from Ruby versions I'm not using to be quite annoying.

I think Gary Berhnhardt is right that [gems should be for installing dependencies, not for installing executables](https://twitter.com/garybernhardt/status/395739598787055616)

I'm proposing that with Parity 0.10.0 or 1.0.0 that we distribute a gem with a post-install message advising users to install the executable as a package (built themselves or from apt/brew/etc), and no longer distribute Parity through Rubygems.

**Comment by bernerdschaefer** [comment]
I fully support this.

I prefer command-line tools to be distributed by system package managers. It's particularly good for Ruby tools like Parity, since I frequently switch between different sets of gems and ruby versions, but always want Parity around.
