### ISSUE TITLE
Match Travelling Ruby

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#78]
In 95ac59c9639bc22a89a411d4326873fc3b834700 we updated to use Ruby 2.3.0. We probably need to downgrade this to 2.2.2 to match Travelling Ruby's latest version.

@JoelQ @tabfugnic @croaky thoughts? I'm open to other solutions if we don't think Traveling Ruby is the right solution, but thus far I think packaging the gem has been a big win.

**Comment by JoelQ** [comment]
Downgrading seems reasonable. In the future we may want to move off of Traveling Ruby but I think the easiest/correct change here is to downgrade. I'd love to hear @croaky and @tabfugnic's thoughts though.

**Comment by tabfugnic** [comment]
@JoelQ I agree with you. Since we are keeping to traveling ruby it makes sense to me to downgrade. Likewise I would hope that we can move off of that at some point.
