### ISSUE TITLE
parity exits on ctrl-c during long-running tasks

### ISSUE THREAD

**Issue by bernerdschaefer** [thoughtbot/parity#79]
For example:

```
$ staging pg:psql
---> Connecting to HEROKU_POSTGRESQL_BRONZE_URL (DATABASE_URL)
psql (9.4.4, server 9.3.9)
SSL connection (protocol: TLSv1.2, cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

myapp-staging::BRONZE=> ^Clib/parity/environment.rb:30:in `system': Interrupt
        from lib/parity/environment.rb:30:in `run_via_cli'
        from lib/parity/environment.rb:17:in `run'
        from bin/staging:8:in `<main>'
```

If you run `heroku pg:psql -a myapp-staging` and hit `ctrl-C` it works as expected -- clearing any partial commands, but leaving the postgres CLI running.

Some ideas for addressing this:

* `parity` captures and forwards received signals to the commands it runs
* `parity` uses `exec` to run commands it passes through to `heroku`.

The second option is likely easier, and possibly more correct, assuming that we don't expect to do anything else after we run the command.

**Comment by geoffharcourt** [comment]
Interesting. Is there any risk to getting stuck if the SSH session on the other end is unresponsive?

**Comment by bernerdschaefer** [comment]
> Is there any risk to getting stuck if the SSH session on the other end is unresponsive?

If we can switch to `exec`, then it would be up to however the `heroku` command handles that, which I think is ideal.

**Comment by geoffharcourt** [comment]
@bernerdschaefer I am going to try to get this in for 1.0.0, I've been running into the same issue.
