### ISSUE TITLE
restore-from errors

### ISSUE THREAD

**Issue by thejones** [thoughtbot/parity#85]
I get a Heroku error when running restore-from. 
OSX 10.11.3
Everything else seems to work as expected and I am not sure how to tell if this is a local issue. 

development restore-from staging
```
 !    `restore-from` is not a heroku command.
 !    See `heroku help` for a list of available commands.
```

development restore staging: 
```
pg_dump: reading schemas
pg_dump: reading user-defined tables
...
```

**Comment by macklinu** [comment]
How have you installed `parity`? I installed via Homebrew, and the output of `brew info parity` is:

```
thoughtbot/formulae/parity: stable 0.9.2.1
https://github.com/thoughtbot/parity
/usr/local/Cellar/parity/0.9.2.1 (1,012 files, 17.7M) *
  Built from source
From: https://github.com/thoughtbot/homebrew-formulae/blob/master/Formula/parity.rb
==> Dependencies
Required: git, heroku-toolbelt, postgres
```

It looks like the `restore-from` command was introduced in be954aabacd765ad8564b21675895ab12638f179, which is in the `v0.9.3.beta` tag, so your version of `parity` might not contain this alias.

**Comment by thejones** [comment]
Sounds good. I did not realize it was introduced in the beta tag. Thank you!
