### ISSUE TITLE
uninitialized constant Parity::Backup::ERB (NameError)

### ISSUE THREAD

**Issue by macklinu** [thoughtbot/parity#86]
I attempted to install `0.9.3.beta` from Homebrew (after seeing thoughtbot/homebrew-formulae@fcb0f7f8fac5f51066c69b9574be459414861a2e). With a previously installed version of `0.9.2.1`, I ran:

```
brew install --devel parity
```

Now the `restore`/`restore-from` commands result in an error.

Running `development restore production` or `development restore-from production` yields:

```
/Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/backup.rb:76:in `parsed_database_yml': uninitialized constant Parity::Backup::ERB (NameError)
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/backup.rb:68:in `development_db'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/backup.rb:42:in `drop_development_database'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/backup.rb:37:in `restore_to_development'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/backup.rb:15:in `restore'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/environment.rb:68:in `restore'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/environment.rb:23:in `run_command'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/lib/parity/environment.rb:12:in `run'
	from /Users/macklinu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parity-0.9.3.beta/bin/development:8:in `<top (required)>'
	from /Users/macklinu/.rbenv/versions/2.2.4/bin/development:23:in `load'
	from /Users/macklinu/.rbenv/versions/2.2.4/bin/development:23:in `<main>'
```

I can still run other parity commands, like `staging tail` successfully.

I'm not 100% sure about how to test a fix for this issue, but I believe it's due to [this line in `lib/parity/backup.rb`](https://github.com/thoughtbot/parity/blob/v0.9.3.beta/lib/parity/backup.rb#L76), and adding `require "erb"` to `lib/parity.rb` might fix it. I'll open a PR for that change.

**Comment by macklinu** [comment]
This seems to be a conflict from previously adding parity to a project's Gemfile, as the path in the comment above points to where my gems are installed, not to Homebrew's Cellar (`/usr/local/Cellar/parity`).

I don't know if this is necessarily an issue then. I closed #87 in the mean time. If you have any tips on testing this locally, I would be glad to test those out!

**Comment by geoffharcourt** [comment]
Hi @macklinu I'm still working out getting gem dependencies to install through Homebrew (hence the development build). When that issue is solved (feel free to take a look at the wrapper scripts in the packaging if you want to help me out!), we'll be able to install beta versions through Homebrew with the `--devel` flag.

**Comment by geoffharcourt** [comment]
I'm going to close this, but if you want to discuss we should do so on an issue on https://github.com/thoughtbot/homebrew-formulae.
