### ISSUE TITLE
Non-functional on Ubuntu

### ISSUE THREAD

**Issue by croaky** [thoughtbot/parity#96]
```
gem install parity
rbenv rehash
development restore production
cannot load such file -- git (LoadError)
```

https://github.com/thoughtbot/parity/blob/master/lib/parity.rb#L7

Maybe a problem with how we're handling load path?

**Comment by geoffharcourt** [comment]
I think you're right. I've had some trouble since we added gem dependencies. Next investment day I'm hoping to roll some of this back to get everyone on the same page.

**Comment by hafizio** [comment]
I experienced the same issue after updating to `ruby 2.3.1`. It was working fine in `ruby 2.3` previously.

**Comment by geoffharcourt** [comment]
@croaky @hafizio can you install v0.10.0 and test on Ubuntu? I've removed external dependencies, so I expect your issues should be resolved.
